### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by ngauthier** [LyricalSecurity/gigo#2]
Hey, I wanted to try this package out, but I could not install it.

```
$ go get -v github.com/LyricalSecurity/gigo
github.com/LyricalSecurity/actions (download)
Username for 'https://github.com': 
```

`go get` tries to get `LyricalSecurity/actions` which is not a public repo, it's embedded into `gigo` but `go get` doesn't know that, it looks for the real repo.

If I cd to the now cloned but not built project:

```
$ sh build.sh 
main.go:7:3: cannot find package "github.com/LyricalSecurity/actions" in any of:
	/usr/local/go/src/github.com/LyricalSecurity/actions (from $GOROOT)
	<mygopath>/src/github.com/LyricalSecurity/actions (from $GOPATH)
```

I'm assuming it's because you use some kind of import rewriting, and this import fails:

https://github.com/LyricalSecurity/gigo/blob/master/main.go#L7

Also note that your build instructions are not idiomatic go. I should be able to `go install github.com/LyricalSecurity/gigo` and have the binary in my $GOPATH/bin. I should not have to run your build script and copy the binary into my path.

**Comment by chayim** [comment]
Hi,

go get definitely won't work with this in its current state - though I can see that changing easily enough in the future. What version of go are you trying this with? We're working off of go 1.4.2- where it appears to work on the variety of platforms we support.

**Comment by ngauthier** [comment]
I'm on 1.4.2 and linux.

Have you tried completely removing gigo before installing it? May be a catch 22 scenario.

**Comment by ngauthier** [comment]
Here is a dockerfile that reproduces it:

```dockerfile
FROM golang:1.4.2
RUN go get -v github.com/LyricalSecurity/gigo
```

Command:

```
$ docker build -t gigo .
Sending build context to Docker daemon 97.79 kB
Sending build context to Docker daemon 
Step 0 : FROM golang:latest
 ---> 121a93c90463
Step 1 : RUN go get -v github.com/LyricalSecurity/gigo
 ---> Running in 72dcdd182bbf
github.com/LyricalSecurity/gigo (download)
github.com/LyricalSecurity/actions (download)
# cd .; git clone https://github.com/LyricalSecurity/actions /go/src/github.com/LyricalSecurity/actions
Cloning into '/go/src/github.com/LyricalSecurity/actions'...
fatal: could not read Username for 'https://github.com': No such device or address
package github.com/LyricalSecurity/gigo
	imports github.com/LyricalSecurity/actions: exit status 128
github.com/codegangsta/cli (download)
INFO[0001] The command [/bin/sh -c go get -v github.com/LyricalSecurity/gigo] returned a non-zero code: 1 
```

**Comment by chayim** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Nuts - as am I. We did exactly that (repeatedly) prior to publish, and
I did it again with our current repository, just in case.

On 15-05-01 03:59 PM, Nick Gauthier wrote:
> I'm on 1.4.2 and linux.
> 
> Have you tried completely removing gigo before installing it? May
> be a catch 22 scenario.
> 
> --- Reply to this email directly or view it on GitHub: 
> https://github.com/LyricalSecurity/gigo/issues/2#issuecomment-98220390
>
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2.0.22 (GNU/Linux)

iEYEARECAAYFAlVD254ACgkQ1rPjlpT926irlwCeMZUcCrrq8UFXD1qHy1rhNZgx
uzgAmwZoYaBE/3dJYTUNPGMe1ZKzUM6s
=rzA3
-----END PGP SIGNATURE-----

**Comment by chayim** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Brilliant - thanks. I can hack on that later.

- --c

On 15-05-01 04:01 PM, Nick Gauthier wrote:
> Here is a dockerfile that reproduces it:
> 
> ```dockerfile FROM golang:1.4.2 RUN go get -v
> github.com/LyricalSecurity/gigo ```
> 
> Command:
> 
> ``` $ docker build -t gigo . Sending build context to Docker daemon
> 97.79 kB Sending build context to Docker daemon Step 0 : FROM
> golang:latest ---> 121a93c90463 Step 1 : RUN go get -v
> github.com/LyricalSecurity/gigo ---> Running in 72dcdd182bbf 
> github.com/LyricalSecurity/gigo (download) 
> github.com/LyricalSecurity/actions (download) # cd .; git clone
> https://github.com/LyricalSecurity/actions
> /go/src/github.com/LyricalSecurity/actions Cloning into
> '/go/src/github.com/LyricalSecurity/actions'... fatal: could not
> read Username for 'https://github.com': No such device or address 
> package github.com/LyricalSecurity/gigo imports
> github.com/LyricalSecurity/actions: exit status 128 
> github.com/codegangsta/cli (download) INFO[0001] The command
> [/bin/sh -c go get -v github.com/LyricalSecurity/gigo] returned a
> non-zero code: 1 ```
> 
> --- Reply to this email directly or view it on GitHub: 
> https://github.com/LyricalSecurity/gigo/issues/2#issuecomment-98220665
>
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2.0.22 (GNU/Linux)

iEYEARECAAYFAlVD284ACgkQ1rPjlpT926js+gCgtUBBdv2nXQTb8lsX6UQRJY6v
TN0AoOsbcAeTH5RwwC1nWsUVckczlANG
=GYSA
-----END PGP SIGNATURE-----

**Comment by ngauthier** [comment]
Great! Figured it was the MVP of reproduction examples.

**Comment by martinellison** [comment]
Same problem as original poster.

**Comment by crsmithdev** [comment]
Same problem
